data("Journals", package = "AER")
Journals <- transform(Journals,
                      age = 2000 - foundingyear,
                      chars = charpp * pages,
                      lpc = log(price/citations),
                      logsubs = log(subs))

library(partykit)
#library(mob)
j_tree <- lmtree(logsubs ~ lpc | price + citations +
                   + age + chars + society, data = Journals, minsize = 10, verbose = TRUE)

#j_tree <- lmtree(logsubs ~ lpc | citations, data = Journals, minsize = 10, verbose = TRUE)

plot(j_tree)
## semtree

library(semtree)

Journals <- Journals[,c("price","citations","age","chars","society","logsubs","lpc")]


#summary(lm(lpc~logsubs, Journals))

summary(lm(logsubs~lpc, Journals))

#
# This model specification was automatically generated by Onyx
# 
require("OpenMx");
manifests<-c("lpc","logsubs")
latents<-c()
model <- mxModel("Unnamed_Model", 
                 type="RAM",
                 manifestVars = manifests,
                 latentVars = latents,
                 mxPath(from="lpc",to=c("logsubs"), 
                        free=c(TRUE), value=c(1.0) , arrows=1, label=c("b1") ),
                 mxPath(from="lpc",to=c("lpc"), 
                        free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_lpc") ),
                 mxPath(from="logsubs",to=c("logsubs"), free=c(TRUE), 
                        value=c(1.0) , arrows=2, label=c("Residual") ),
                 mxPath(from="one",
                        to=c("lpc","logsubs"), label=c("MEAN_lpc","b0"),
                        free=TRUE, value=0, arrows=1),
                 mxData(Journals, type = "raw")
);

result <- mxRun(model)
summary(result)

control <- semtree.control(method = "score")


tree.unc <- semtree(model=model, data= Journals, control =control)

tree.foc <- semtree(model=model, data= Journals, 
                    control=control,constraints=list(focus.parameters="b1"))

tree.foc_2coef <- semtree(model=model, data= Journals, 
                    control=control,constraints=list(focus.parameters=c("b0","b1")))


plot(prune(tree.foc,1))

plot(tree.unc)
plot(tree.foc)

saveRDS(tree.unc, file = "data/02_tree_unc.rds")
saveRDS(tree.foc, file = "data/02_tree_foc.rds")
saveRDS(tree.foc_2coef, file = "data/02_tree_foc_2coef.rds")


#data("Journals", package = "AER")
Journals[, "ind"]<-ifelse(Journals$citations>=371.5 & Journals$citations<972.5 & Journals$price<164, 1,0)
Journals$ind <- as.factor(Journals$ind)
library(tidyr)
library(ggplot2)

Journals %>% ggplot(aes(x=lpc, y=logsubs, group=ind, color=ind))+geom_point()
