#
# This model specification was automatically generated by Onyx
# 
require("OpenMx");

manifests<-c("x1","x2","x3","x4","x5","x6","x7","x8","x9")

N <-100
modelData <- data.frame(matrix(rnorm(N*9),ncol=9))
names(modelData) <- manifests

latents<-c("icept","slope","o1","o2","o3")
model <- mxModel("Unnamed_Model", 
                 type="RAM",
                 manifestVars = manifests,
                 latentVars = latents,
                 mxPath(from="icept",to=c("o1","o2","o3"), free=c(FALSE,FALSE,FALSE), value=c(1.0,1.0,1.0) , arrows=1, label=c("icept__o1","icept__o2","icept__o3") ),
                 mxPath(from="slope",to=c("o2","o3"), free=c(FALSE,FALSE), value=c(1.0,2.0) , arrows=1, label=c("slope__o2","slope__o3") ),
                 mxPath(from="o1",to=c("x1","x2","x3"), free=c(FALSE,TRUE,TRUE), value=c(1.0,1.0,1.0) , arrows=1, label=c("o1__x1","a","b") ),
                 mxPath(from="o2",to=c("x4","x5","x6"), free=c(FALSE,TRUE,TRUE), value=c(1.0,1.0,1.0) , arrows=1, label=c("o2__x4","a","b") ),
                 mxPath(from="o3",to=c("x7","x8","x9"), free=c(FALSE,TRUE,TRUE), value=c(1.0,1.0,1.0) , arrows=1, label=c("o3__x7","a","b") ),
                 mxPath(from="one",to=c("icept","slope"), free=c(TRUE,TRUE), value=c(1.0,1.0) , arrows=1, label=c("const__icept","const__slope") ),
                 mxPath(from="one",to=c("x1","x2","x3","x4","x5","x6","x7","x8","x9"), free=c(FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE), value=c(1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0) , arrows=1, label=c("const__x1","c","d","const__x4","c","d","const__x7","c","d") ),
                 mxPath(from="icept",to=c("slope","icept"), free=c(TRUE,TRUE), value=c(0,1.0) , arrows=2, label=c("COV_icept_slope","sigma_i") ),
                 mxPath(from="slope",to=c("slope"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("sigma_s") ),
                 mxPath(from="o1",to=c("o1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("e") ),
                 mxPath(from="o2",to=c("o2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("e") ),
                 mxPath(from="o3",to=c("o3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("e") ),
                 mxPath(from="x1",to=c("x1"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x1") ),
                 mxPath(from="x2",to=c("x2"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x2") ),
                 mxPath(from="x3",to=c("x3"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x3") ),
                 mxPath(from="x4",to=c("x4"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x4") ),
                 mxPath(from="x5",to=c("x5"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x5") ),
                 mxPath(from="x6",to=c("x6"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x6") ),
                 mxPath(from="x7",to=c("x7"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x7") ),
                 mxPath(from="x8",to=c("x8"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x8") ),
                 mxPath(from="x9",to=c("x9"), free=c(TRUE), value=c(1.0) , arrows=2, label=c("VAR_x9") ),
                 mxData(modelData, type = "raw")
);

result <- mxRun(model)
summary(result)

getModel <- function(model, a=1, b=1, c=1, d=1, e=1, res=1, slope_var=1) {

# second item loading a: 1
model <- omxSetParameters(model, labels="a", values=a)

# third item loading b: 1
model <- omxSetParameters(model, labels="b", values=b)

# first item intercept c: 1
model <- omxSetParameters(model, labels="c", values=c)

# second item intercept d: 1
model <- omxSetParameters(model, labels="d", values=d)

# occasion-specific residual: e
model <- omxSetParameters(model, labels="e", values=e)

for (i in 1:9) {
  model <- omxSetParameters(model, labels=paste0("VAR_x",i), values=res)
  
}

model <- omxSetParameters(model, labels="sigma_s", values=slope_var)


return(model)
}

Ng <- 200
dat1 <- mxGenerateData(getModel(model,slope_var=2, res=1,e=1),nrows = Ng)
dat2 <- mxGenerateData(getModel(model,slope_var=10, res=1,e=1),nrows = Ng)
dat3 <- mxGenerateData(getModel(model,slope_var=2, res=20,e=1),nrows = Ng)
dat4 <- mxGenerateData(getModel(model,slope_var=10,res=20,e=1),nrows = Ng)
dat5 <- mxGenerateData(getModel(model,slope_var=2, res=1, e=1),nrows = Ng)
dat6 <- mxGenerateData(getModel(model,slope_var=10, res=1, e=1),nrows = Ng)
dat7 <- mxGenerateData(getModel(model,slope_var=2, res=20, e=1),nrows = Ng)
dat8 <- mxGenerateData(getModel(model,slope_var=10,res=20, e=1),nrows = Ng)



pred1 <- rep(c(0,1,0,1,0,1,0,1),each=Ng)
pred2 <- rep(c(0,0,1,1,0,0,1,1),each=Ng)
pred3 <- rep(c(0,0,0,0,1,1,1,1),each=Ng)
df<-data.frame(rbind(dat1,dat2,dat3,dat4),pred1,pred2,pred3)
#df$pred1 <- as.factor(pred1)
#df$pred2 <- as.factor(pred2)
#df$pred3 <- as.factor(pred3)

for (i in 1:(Ng*4)) {
  qd <- runif(1,0,4)
  df[i,1:9] <- df[i,1:9]+  rep(c(0,1/4,1),each=3)*qd
}

df$id <- 1:nrow(df)

summary(mxRun(model=model))

tree<-semtree(model, data=df, control = semtree.control(method="score"))

# this is supposed to split according to at least two predictors, probably pred1, pred2
plot(tree)

tree2<-semtree(model, data=df, control = semtree.control(method="score"),
              constraints=semtree.constraints(focus.parameters = "sigma_s"))

# this is supposed to split only according to pred1
plot(tree2)

vars <- paste0("VAR_x",1:9)
tree3<-semtree(model, data=df, control = semtree.control(method="naive"),
               constraints=semtree.constraints(focus.parameters = c("sigma_s",vars)))

# this is supposed to split only according to pred3
plot(tree3)


df %>% pivot_longer(1:9) %>% ggplot(aes(x=name,y=value,group=id))+geom_line()+facet_wrap(~pred1)


df %>%as_tibble()%>% pivot_longer(1:9) %>% dplyr::filter(id<10) %>% ggplot(aes(x=name,y=value,group=id))+geom_line()+facet_wrap(~pred3)
